# Generated by Django 4.1.2 on 2022-10-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing1', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('candy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.candy')),
            ],
        ),
    ]
