# Generated by Django 4.1.2 on 2022-10-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['-exp_date']},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='exp_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
    ]
