# Generated by Django 4.1.2 on 2022-10-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_brand_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='brand',
            field=models.ManyToManyField(to='main_app.brand'),
        ),
    ]
